name: Use Secrets in GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Access Secrets
        run: |
          echo "API_KEY: ${{ secrets.API_KEY }}"
          echo "DB_PASSWORT: (Hidden)"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_PASSWORT: ${{ secrets.DB_PASSWORT }}
